config/routes.rb
ProformaDA::Application.routes.draw do

  resources :disbursements do
    member do
      match 'status/:status' => 'disbursements#status', via: [:get, :post]
      get 'print'
      get 'access_log'
      match 'revisions(/:number)' => 'disbursements#revisions', via: [:get, :post]
    end
    collection do
      match 'search' => "disbursements#search", via: [:get, :post]
    end
  end
  match 'proforma_disbursements/:id(/:revision_number)' => 'disbursements#published', :as => :published, via: [:get, :post]
  match 'pfda/:id(/:revision_number)' => 'disbursements#published', :as => :published_short, via: [:get, :post]
  match 'pda/:id(/:revision_number)' => 'disbursements#published', :as => :published_short_2, via: [:get, :post]

  get 'api/ping' => "api#ping"
  match 'api/nominations' => "api#nominations", via: [:get, :post]
  match 'api/nomination_details' => "api#nomination_details", via: [:get, :post]
  match 'api/agency_fees' => "api#agency_fees", via: [:get, :post]

  resources :ports do
    resources :terminals do
      resources :services do
        collection do
          post 'sort'
        end
      end
      resources :tariffs
    end
    resources :services do
      collection do
        post 'sort'
      end
    end
    resources :tariffs
  end
  resources :vessels do
    collection do
      get 'search/:name', to: "vessels#search"
    end
  end
  resources :companies do
    collection do
      get 'search/:name', to: "companies#search"
    end
  end
  resources :taxes
  resources :cargo_types do
    collection do
      post 'enabled'
    end
  end
  resources :named_services do
    collection do
      post 'sort', to: "services#sort"
    end
  end

  post 'jsonrpc' => 'jsonrpc#index'

  post 'auth/register' => 'auth#register'
  get 'auth/login' => 'auth#login'
  get 'auth/logout' => 'auth#logout'
  post 'auth/authenticate' => 'auth#authenticate'

  get "home/index"
  get "landing/index"

  get "vessel_types/vessel_subtype", to: "vessel_types#vessel_subtype"

  root :to => 'home#index'

end

app/models/service.rb
class Service < ActiveRecord::Base
  include RankedModel
  attr_accessor :changelog
  attr_accessor :tax_applies
  validates_presence_of :key, :item
  validate :code_checks
  belongs_to :port, counter_cache: true
  belongs_to :terminal
  belongs_to :user
  belongs_to :activity_code
  belongs_to :tenant
  belongs_to :company
  has_many :service_updates
  mount_uploader :document, TariffUploader
  ranks :row_order, :with_same => [:port_id, :terminal_id]
  def mockup_context
    <<CTX
    var ctx = {
      vessel: {
        nrt: #{Random.rand(100000.0).round(2)},
        grt: #{Random.rand(100000.0).round(2)},
        dwt: #{Random.rand(100000.0).round(2)},
        loa: #{Random.rand(300.0).round(1)}
      },
      estimate: {
        eta: new Date(#{"\""}#{DateTime.now}#{"\""}),
        cargo_qty: #{Random.rand(50000.0).round(2)},
        tugs_in: #{Random.rand(10)},
        tugs_out: #{Random.rand(10)},
        loadtime: #{Random.rand(100)},
        days_alongside: #{Random.rand(3)}
      },
      cargo_type: {
        type: "",
        subtype: "",
        subsubtype: "",
        subsubsubtype: ""
      },
      data: {
      }
    };
CTX
  end

  def code_checks
    ctx = V8::Context.new
    ctx.eval(mockup_context)
    begin
      ctx.eval("var c = #{self.code};")
    rescue Exception => e
      errors.add(:code, "Syntax Error: #{e.message}")
      return
    end
    begin
      ctx.eval("c.compute(ctx)")
    rescue Exception => e
      errors.add(:code, "Runtime Error: #{e.message}")
    end
  end

  def name
    item
  end

  def tax_applies
    self.code.include? "taxApplies: true"
  end

  def as_json
    { "item" => self.item,
      "key" => self.key,
      "taxApplies" => self.tax_applies,
      "compulsory" => self.compulsory
    }
  end

  def get_activity_code
    return self.key if self.tenant.use_service_key_as_activity_code?
    self.activity_code.code rescue 'MISC'
  end
end

app/controllers/services_controller.rb
class ServicesController < NestedCommonController

  def sort
    @instance = current_tenant.services.find(params[:id])
    @instance.row_order_position = params[:row_order_position]
    @instance.save
    render nothing: true
  end


  private
  def new_instance
    super()
    @instance.code = "{\n  compute: function(ctx) {\n    return 0;\n  },\n  taxApplies: false\n}\n"
    @instance.changelog = 'Initial service definition'
    @instance
  end

  def parse_params
    @old_code = @instance.code rescue ''
    @changelog = params[:service].delete(:changelog)
  end

  def successful_save
    update = ServiceUpdate.new()
    update.tenant_id = current_tenant.id
    update.service = @instance
    update.user = current_user
    update.changelog = @changelog
    update.document_from_service(@instance) 
    update.old_code = @old_code
    update.new_code = @instance.code
    update.save!
  end

  def model
    Service
  end

  def safe_params
    params.require(:service).permit(:code, :item, :key, :row_order, :disabled, 
                                    :activity_code_id, :company_id,
                                    :document, :compulsory)
  end
end

app/views/services/_form.html.erb
<%= simple_form_for(@terminal.nil? ? [@port, @instance] : [@port, @terminal, @instance]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :item %>
    <%= f.input :key %>
    <%= f.association :company, :as => :collection_select, 
    collection: Company.where(is_supplier: true),
    label: "Supplier" %>
    <%= f.association :activity_code,
                      label: "On Account Activity Code",
                      label_method: :display %>
    <%= f.input :compulsory %>
    <div class="disabled-field">
      <%= f.input :disabled, label: "Disabled by default" %>
    </div>
    <%= f.input :code, :as => :editor_ace %>
    <%= f.input :document %>
    <%= f.input :changelog, label: 'Change Log Message' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
  <script type="text/javascript">
    $('select#service_activity_code_id').select2();
    $('select#service_company_id').select2();

    $('input#service_compulsory').change(onCompulsoryCheckboxChange);

    function onCompulsoryCheckboxChange(event) {
      if ($("input#service_compulsory").is(':checked')) {
        $("div.disabled-field").hide();
        $("input#service_disabled").prop('checked', false);
       } else {
        $("div.disabled-field").show();
       }
    }

  </script>
<% end %>

app/views/services/edit.html.erb
<% content_for :navbar_buttons do %>
  <% if @terminal %>
    <%= link_to 'View', port_terminal_service_path(@port, @terminal, @instance), :class => "btn btn-default btn-sm" %>
    <%= link_to 'Back', port_terminal_services_path(@port, @terminal), :class => "btn btn-default btn-sm" %>
  <% else %>
    <%= link_to 'View', port_service_path(@port, @instance), :class => "btn btn-default btn-sm" %>
    <%= link_to 'Back', port_services_path(@port), :class => "btn btn-default btn-sm" %>
  <% end %>
<% end %>
<div class="row">
  <div class="col-md-12">
    <h2 class="title">Editing Service for <%= @port.name %><%= " / #{@terminal.name}" if @terminal %></h2>

    <%= render 'form' %>
  </div>
</div>

app/views/services/index.html.erb
<% content_for :navbar_buttons do %>
  <% if @terminal %>
    <%= link_to 'New Service',
                new_port_terminal_service_path(@port, @terminal),
                :class => 'btn btn-primary btn-sm' %>
  <% else %>
    <%= link_to 'New Service', new_port_service_path(@port),
                :class => 'btn btn-primary btn-sm' %>
  <% end %>
<% end %>
<div class="row">
  <div class="col-md-12">
    <table class="table table-bordered" id="sortable"
          data-update_url="<%= @terminal.nil? ? sort_port_services_path(@port) : sort_port_terminal_services_path(@port, @terminal) %>"
          data-object_type="service">
      <thead>
        <tr>
          <th>Item</th>
          <th>Key</th>
          <th>Activity Code</th>
          <th>Compulsory</th>
          <th>Reference Document</th>
          <th>Created By</th>
          <th>Last Modified</th>
          <th>Last Modified By</th>
          <th>Last Change</th>
          <th>Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @instances.each do |service| %>
        <tr class="item" data-item_id="<%= service.id %>">
          <td><%= link_to service.item, @terminal.nil? ? port_service_url(@port, service) : port_terminal_service_url(@port, @terminal, service) %></td>
          <td><%= service.key %></td>
          <td><%= service.activity_code.code rescue "" %></td>
          <td><%= service.compulsory ? 'Yes' : 'No' %></td>
          <td><%= link_to(File.basename(service.document.path), service.document.url) rescue '' %></td>
          <td><%= service.user.full_name rescue 'N/A' %></td>
          <td><%= l service.updated_at %></td>
          <td><%= service.service_updates.last.user.full_name rescue 'N/A' %></td>
          <td><%= service.service_updates.last.changelog rescue 'N/A' %></td>
          <td>
            <div class="btn-group" style="whitespace: no-wrap;">
              <% if @terminal %>
                <%= link_to icon('eye-open'),
                            port_terminal_service_path(@port, @terminal, service),
                            class: 'btn btn-info btn-sm',
                            title: 'View' %>
                <%= link_to icon('pencil'),
                            edit_port_terminal_service_path(@port, @terminal, service),
                            class: 'btn btn-default btn-sm',
                            title: 'Edit' %>
                <%= link_to icon('trash'),
                            port_terminal_service_path(@port, @terminal, service),
                            method: :delete, data: { confirm: 'Are you sure?' },
                            class:'btn btn-danger btn-sm',
                            title: 'Delete' %>
              <% else %>
                <%= link_to icon('eye-open'), port_service_path(@port, service),
                            class: 'btn btn-info btn-sm',
                            title: 'View' %>
                <%= link_to icon('pencil'),
                            edit_port_service_path(@port, service),
                            class: 'btn btn-default btn-sm',
                            title: 'Edit' %>
                <%= link_to icon('trash'),
                            port_service_path(@port, service), method: :delete,
                            data: { confirm: 'Are you sure?' },
                            class: 'btn btn-danger btn-sm',
                            title: 'Delete' %>
              <% end %>
            </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<script type="text/javascript">
    $("table.table").dataTable({bSort: false, bPaginate: false});
</script>

app/views/services/new.html.erb
<% content_for :navbar_buttons do %>
  <% if @terminal %>
    <%= link_to 'Back', port_terminal_services_path(@port, @terminal), :class => 'btn btn-default btn-sm' %>
  <% else %>
    <%= link_to 'Back', port_services_path(@port), :class => 'btn btn-default btn-sm' %>
  <% end %>
<% end %>
<div class="row">
  <div class="col-md-12">
  <h2 class="title">New Service for <%= @port.name %><%= " / #{@terminal.name}" if @terminal %></h2>

  <%= render 'form' %>
  </div>
</div>

app/views/services/show.html.erb
<% content_for :navbar_buttons do %>
  <% if @terminal %>
    <%= link_to 'Edit', edit_port_terminal_service_path(@port, @terminal, @instance), :class => "btn btn-primary btn-sm" %>
    <%= link_to 'Back', port_terminal_services_path(@port, @terminal), :class => "btn btn-default btn-sm" %>
  <% else %>
    <%= link_to 'Edit', edit_port_service_path(@port, @instance), :class => "btn btn-primary btn-sm" %>
    <%= link_to 'Back', port_services_path(@port), :class => "btn btn-default btn-sm" %>
  <% end %>
<% end %>
<div class="row">
  <div class="col-md-12">
    <h2 class="title">Service for <%= @port.name %><%= " / #{@terminal.name}" if @terminal %></h2>
    <% ['item', 'key'].each do |k| %>
      <p><strong><%= k.capitalize %>:</strong> <%= @instance.send(k) %></p>
    <% end %>
    <p><strong>Supplier:</strong> <%= @instance.company.name rescue 'N/A' %></p>
    <p><strong>Compulsory:</strong> <%= @instance.compulsory ? 'Yes' : 'No' %></p>
    <p><strong>Disabled by Default:</strong> <%= @instance.disabled ? 'Yes' : 'No' %></p>
    <p><strong>Reference Document:</strong> <%= link_to(File.basename(@instance.document.path), @instance.document.url) rescue 'N/A' %></p>

    <p><strong>Created By:</strong> <%= @instance.user.full_name rescue 'N/A' %></p>
    <p><strong>Created On:</strong> <%= l @instance.created_at %></p>
    <p><strong>Code:</strong></p>
    <div style="height: 440px;">
      <div id="code" data-ace-mode="javascript"><%= @instance.code %></div>
    </div>
    <div class="clearfix"></div>
    <p><strong>Change Log:</strong></p>
    <table class="table">
       <thead>
        <tr>
          <th>Date</th>
          <th>Author</th>
          <th>Change Log Message</th>
          <th>Reference Document</th>
          <th class="hide">Code</th>
        </tr>
      </thead>
      <tbody>
      <% @instance.service_updates.order('created_at DESC').each do |u| %>
        <tr>
          <td><%= l u.created_at %></td>
          <td><%= u.user.full_name rescue 'N/A' %></td>
          <td><%= u.changelog %></td>
          <td><%= link_to(File.basename(u.document.path), u.document.url) rescue 'N/A' %></td>
          <td class="hide"> 
            <% if u.old_code.present? %>
              <pre><%= u.old_code %></pre> 
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>
<script type="text/javascript">
  var editor = ace.edit("code");
  editor.setTheme("ace/theme/clouds");
  editor.setReadOnly("true");
  editor.getSession().setUseWorker(false);
  var mode = require("ace/mode/javascript").Mode;
  editor.getSession().setMode(new mode());
</script>