config/routes.rb
ProformaDA::Application.routes.draw do

  resources :disbursements do
    member do
      match 'status/:status' => 'disbursements#status', via: [:get, :post]
      get 'print'
      get 'access_log'
      match 'revisions(/:number)' => 'disbursements#revisions', via: [:get, :post]
    end
    collection do
      match 'search' => "disbursements#search", via: [:get, :post]
    end
  end
  match 'proforma_disbursements/:id(/:revision_number)' => 'disbursements#published', :as => :published, via: [:get, :post]
  match 'pfda/:id(/:revision_number)' => 'disbursements#published', :as => :published_short, via: [:get, :post]
  match 'pda/:id(/:revision_number)' => 'disbursements#published', :as => :published_short_2, via: [:get, :post]

  get 'api/ping' => "api#ping"
  match 'api/nominations' => "api#nominations", via: [:get, :post]
  match 'api/nomination_details' => "api#nomination_details", via: [:get, :post]
  match 'api/agency_fees' => "api#agency_fees", via: [:get, :post]

  resources :ports do
    resources :terminals do
      resources :services do
        collection do
          post 'sort'
        end
      end
      resources :tariffs
    end
    resources :services do
      collection do
        post 'sort'
      end
    end
    resources :tariffs
  end
  resources :vessels do
    collection do
      get 'search/:name', to: "vessels#search"
    end
  end
  resources :companies do
    collection do
      get 'search/:name', to: "companies#search"
    end
  end
  resources :taxes
  resources :cargo_types do
    collection do
      post 'enabled'
    end
  end
  resources :named_services do
    collection do
      post 'sort', to: "services#sort"
    end
  end

  post 'jsonrpc' => 'jsonrpc#index'

  post 'auth/register' => 'auth#register'
  get 'auth/login' => 'auth#login'
  get 'auth/logout' => 'auth#logout'
  post 'auth/authenticate' => 'auth#authenticate'

  get "home/index"
  get "landing/index"

  get "vessel_types/vessel_subtype", to: "vessel_types#vessel_subtype"

  root :to => 'home#index'

end

app/models/vessel.rb
class Vessel < ActiveRecord::Base
  default_scope -> {order('name ASC')}
  validates_presence_of :dwt, :grt, :loa, :name, :nrt
  has_many :disbursements
  belongs_to :tenant

  extend Syncable

  def sbt_certified_display
    VesselsHelper.sbt_certified_display(self.sbt_certified)
  end

  def crystalize(d)
    d['data'].merge!({
      "vessel_name" => self.name,
      "vessel_dwt" => self.dwt.to_s,
      "vessel_grt" => self.grt.to_s,
      "vessel_loa" => self.loa.to_s,
      "vessel_nrt" => self.nrt.to_s,
      "vessel_imo" => self.imo_code.to_s,
      "vessel_type" => self.maintype.to_s,
      "vessel_subtype" => self.subtype.to_s,
      "vessel_sbt_certified" => self.sbt_certified.to_s,
    })
  end

  def update_from_json(tenant, data)
    self.tenant_id = tenant.id
    if data['vesselTypeId']
      api = AosApi.new(tenant)
      t = api.find('vesselType', data['vesselTypeId'])
      self.maintype = t["type"] if t
      self.subtype = t["subtype"] if t
    end
    self.remote_id = data['id']
    self.name = data['name']
    self.loa = self.parse_number(data['loa']) if data['loa']
    self.nrt = self.parse_number(data['intlNetRegisteredTonnage']) if data['intlNetRegisteredTonnage']
    self.grt = self.parse_number(data['intlGrossRegisteredTonnage']) if data['intlGrossRegisteredTonnage']
    self.dwt = self.parse_number(data['fullSummerDeadweight']) if data['fullSummerDeadweight']
    self.sbt_certified = data['sbtCertified'] if data['sbtCertified']
    self.imo_code = data['imoCode'] if data['imoCode']
    self.sbt_certified = data['sbtCertified']
  end

  def self.aos_modify(tenant, data)
    i = Vessel.where(tenant_id: tenant.id, remote_id: data['id']).first
    i = Vessel.new if i.nil? and valid_data(data)
    i.update_from_json(tenant, data)
    i.save
  end

  def parse_number(val)
    return val unless val.present?
    # remove thousand separator e.g. "1,684""
    val.to_s.tr(',','')
  end
  
  private
  def self.valid_data(data)
    missing = ['loa', 'intlNetRegisteredTonnage',
     'intlGrossRegisteredTonnage', 'fullSummerDeadweight'].map do |k|
      data[k].nil?
    end
    return false if missing.member? true
    true
  end

end

app/models/vessel_type.rb
class VesselType < ActiveRecord::Base
end

app/controllers/vessels_controller.rb
class VesselsController < CommonController
  before_filter :authenticate_user!
  before_filter :ensure_admin, except: [:search]

  add_breadcrumb "Vessels", :vessels_url

  def model
    Vessel
  end

  # GET /vessels
  # GET /vessels.json
  def index
    @title = "Vessels"
    @vessels_grid = initialize_grid(current_tenant.vessels,
                      order: 'vessels.name',
                      order_direction: 'asc')

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def search
    vessels = current_tenant.vessels
                .where('name ilike :name',
                       name: "%#{params[:name]}%").map do |v|
      {id: v.id, name: v.name}
    end
    render json: vessels
  end

  private
  def safe_params
    params.require(:vessel).permit(:dwt, :grt, :loa, :nrt, :name, :sbt_certified)
  end
end

app/helpers/vessels_helper.rb
module VesselsHelper
  def self.sbt_certified_from_string(sbt_certified_string)
    if sbt_certified_string.nil? or sbt_certified_string == ""
      nil
    elsif sbt_certified_string == "true"
      true
    else
      false
    end
  end
  def self.sbt_certified_display_from_string(sbt_certified_string)
    VesselsHelper.sbt_certified_display(
      VesselsHelper.sbt_certified_from_string(sbt_certified_string)
    )
  end

  def self.sbt_certified_display(sbt_certified)
    if sbt_certified.nil?
      "Not set"
    elsif !sbt_certified
      "No"
    else
      "Yes"
    end
  end
end

app/views/vessels/_actions.html.erb
<div class="btn-toolbar da-actions">
  <div class="btn-group btn-group-sm">
    <%= link_to icon(:pencil), edit_vessel_path(vessel),
      :class => 'btn btn-default btn-sm',
      :title => 'Edit' %>
    <%= link_to icon(:trash), vessel, method: :delete,
              data: { confirm: 'Are you sure?' },
              :class => "btn btn-danger btn-sm#{" disabled" if vessel.disbursements.count > 0}",
              :title => 'Delete' %>
  </div>
</div>

app/views/vessels/_form.html.erb
<%= simple_form_for(@instance) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :loa, label: "LOA" %>
    <%= f.input :grt, label: "GRT" %>
    <%= f.input :nrt, label: "NRT" %>
    <%= f.input :dwt, label: "DWT" %>
    <%= f.input :sbt_certified, label: "SBT Certified", as: :boolean %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/vessels/_grid.html.erb
<%= grid(@vessels_grid) do |g|
  g.column name: 'Name', attribute: 'name' do |v|
    link_to v.name, vessel_path(v)
  end
  g.column name: 'LOA', attribute: 'loa' do |v|
    [v.loa, class: 'text-right']
  end
  g.column name: 'GRT', attribute: 'grt' do |v|
    [v.grt, class: 'text-right']
  end
  g.column name: 'NRT', attribute: 'nrt' do |v|
    [v.nrt, class: 'text-right']
  end
  g.column name: 'DWT', attribute: 'dwt' do |v|
    [v.dwt, class: 'text-right']
  end
  g.column name: 'SBT Certified', attribute: 'sbt_certified' do |v|
    [v.sbt_certified_display, class: 'text-right']
  end
  g.column do |v|
    render partial: 'actions', locals: {vessel: v}
  end
end %>

app/views/vessels/edit.html.erb
<% content_for :navbar_buttons do %>
  <%= link_to 'View', @instance, :class => 'btn btn-default btn-sm' %>
  <%= link_to 'Back', vessels_path, :class => 'btn btn-default btn-sm' %>
<% end %>
<div class="row">
  <div class="col-md-12">
    <h2 class="title">Editing Vessel</h2>

    <%= render 'form' %>

  </div>
</div>

app/views/vessels/index.html.erb
<% content_for :navbar_buttons do %>
  <%= link_to 'New Vessel', new_vessel_path,
              class: 'btn btn-primary btn-sm' %>
<% end %>
<div class="row">
  <div class="col-md-12">
    <%= render partial: 'grid' %>
  </div>
</div>

app/views/vessels/new.html.erb
<% content_for :navbar_buttons do %>
  <%= link_to 'Cancel', vessels_path, :class => "btn btn-default btn-sm" %>
<% end %>
<div class="row">
  <div class="col-md-12">
    <h2 class="title">New Vessel</h2>

    <%= render 'form' %>
  </div>
</div>

app/views/vessels/show.html.erb
<% content_for :navbar_buttons do %>
  <%= link_to 'Edit', edit_vessel_path(@instance), :class => "btn btn-primary btn-sm" %>
  <%= link_to 'Back', vessels_path, :class => "btn btn-default btn-sm" %>
<% end %>
<div class="row">
  <div class="col-md-12">
    <p id="notice"><%= notice %></p>

    <h2 class="title"><%= @instance.name %></h2>
    <p><strong>DWT:</strong> <%= @instance.dwt %></p>
    <p><strong>GRT:</strong> <%= @instance.grt %></p>
    <p><strong>LOA:</strong> <%= @instance.loa %></p>
    <p><strong>NRT:</strong> <%= @instance.nrt %></p>
    <p><strong>SBT Certified:</strong> <%= @instance.sbt_certified_display %></p>
  </div>
</div>