config/routes.rb
ProformaDA::Application.routes.draw do

  resources :disbursements do
    member do
      match 'status/:status' => 'disbursements#status', via: [:get, :post]
      get 'print'
      get 'access_log'
      match 'revisions(/:number)' => 'disbursements#revisions', via: [:get, :post]
    end
    collection do
      match 'search' => "disbursements#search", via: [:get, :post]
    end
  end
  match 'proforma_disbursements/:id(/:revision_number)' => 'disbursements#published', :as => :published, via: [:get, :post]
  match 'pfda/:id(/:revision_number)' => 'disbursements#published', :as => :published_short, via: [:get, :post]
  match 'pda/:id(/:revision_number)' => 'disbursements#published', :as => :published_short_2, via: [:get, :post]

  get 'api/ping' => "api#ping"
  match 'api/nominations' => "api#nominations", via: [:get, :post]
  match 'api/nomination_details' => "api#nomination_details", via: [:get, :post]
  match 'api/agency_fees' => "api#agency_fees", via: [:get, :post]

  resources :ports do
    resources :terminals do
      resources :services do
        collection do
          post 'sort'
        end
      end
      resources :tariffs
    end
    resources :services do
      collection do
        post 'sort'
      end
    end
    resources :tariffs
  end
  resources :vessels do
    collection do
      get 'search/:name', to: "vessels#search"
    end
  end
  resources :companies do
    collection do
      get 'search/:name', to: "companies#search"
    end
  end
  resources :taxes
  resources :cargo_types do
    collection do
      post 'enabled'
    end
  end
  resources :named_services do
    collection do
      post 'sort', to: "services#sort"
    end
  end

  post 'jsonrpc' => 'jsonrpc#index'

  post 'auth/register' => 'auth#register'
  get 'auth/login' => 'auth#login'
  get 'auth/logout' => 'auth#logout'
  post 'auth/authenticate' => 'auth#authenticate'

  get "home/index"
  get "landing/index"

  get "vessel_types/vessel_subtype", to: "vessel_types#vessel_subtype"

  root :to => 'home#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  default_scope -> {order('name ASC')}
  validates_presence_of :name
  has_many :disbursements
  has_many :services
  belongs_to :tenant

  extend Syncable

  FIELDS=['name', 'email', 'prefunding_type', 'prefunding_percent', 'is_supplier']

  def crystalize(d)
    FIELDS.inject(d['data']) {|data,f| data["company_#{f}"] = self.send(f); data }
    d
  end

  def update_from_json(tenant, data)
    self.tenant_id = tenant.id
    self.remote_id = data['id']
    FIELDS.each do |f|
      d = data[f.camelize(:lower)]
      send("#{f}=", d) if d
    end
  end

  def self.aos_modify(tenant, data)
    c = Company.where(tenant_id: tenant.id, remote_id: data['id']).first
    c = Company.new if c.nil?
    c.update_from_json(tenant, data)
    c.save
  end
end

app/controllers/companies_controller.rb
class CompaniesController < CommonController
  before_filter :authenticate_user!
  before_filter :ensure_admin, except: [:search]

  add_breadcrumb "Companies", :companies_url

  def model
    Company
  end

  def index
    @title = "Companies"
    @companies_grid = initialize_grid(current_tenant.companies,
                        order: 'companies.name',
                        order_direction: 'asc')

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def search
    companies = current_tenant.companies.where(
                  'remote_id is not null and name ilike :name',
                  name: "%#{params[:name]}%").map do |c|
      {id: c.id, remote_id: c.remote_id, name: c.name}
    end
    render json: companies
  end

  private
  def safe_params
    params.require(:company).permit(:email, :name, :is_supplier)
  end
end

app/views/companies/_actions.html.erb
<div class="btn-toolbar da-actions">
  <div class="btn-group btn-group-sm">
    <%= link_to icon(:pencil), edit_company_path(company),
      :class => 'btn btn-default btn-sm',
      :title => 'Edit' %>
    <%= link_to icon(:trash), company, method: :delete,
              data: { confirm: 'Are you sure?' },
              :class => "btn btn-danger btn-sm#{" disabled" if company.disbursements.count > 0}",
              :title => 'Delete' %>
  </div>
</div>

app/views/companies/_form.html.erb
<%= simple_form_for(@instance) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :is_supplier, label: "Is Supplier", as: :boolean %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/companies/_grid.html.erb
<%= grid(@companies_grid) do |g|
  g.column name: 'Name', attribute: 'name' do |c|
    link_to c.name, company_path(c)
  end
  g.column name: 'Email', attribute: 'email' do |c|
    link_to c.email, "mailto:#{c.email}" if c.email
  end
  g.column do |c|
    render partial: 'actions', locals: {company: c}
  end
end %>

app/views/companies/edit.html.erb
<% content_for :navbar_buttons do %>
  <%= link_to 'View', @instance, :class => 'btn btn-default btn-sm' %>
  <%= link_to 'Back', companies_path, :class => 'btn btn-default btn-sm' %>
<% end %>
<div class="row">
  <div class="col-md-12">
    <h2 class="title">Editing Company</h2>

    <%= render 'form' %>

  </div>
</div>

app/views/companies/index.html.erb
<% content_for :navbar_buttons do %>
  <%= link_to 'New Company', new_company_path,
              :class => 'btn btn-primary btn-sm' %>
<% end %>
<div class="row">
  <div class="col-md-12">
    <%= render partial: 'grid' %>
  </div>
</div>

app/views/companies/new.html.erb
<% content_for :navbar_buttons do %>
  <%= link_to 'Cancel', companies_path, :class => 'btn btn-default btn-sm' %>
<% end %>
<div class="row">
  <div class="col-md-12">
    <h2 class="title">New Company</h2>

    <%= render 'form' %>
  </div>
</div>

app/views/companies/show.html.erb
<% content_for :navbar_buttons do %>
  <%= link_to 'Edit', edit_company_path(@instance), :class => "btn btn-primary btn-sm" %>
  <%= link_to 'Back', companies_path, :class => "btn btn-default btn-sm" %>
<% end %>
<div class="row">
  <div class="col-md-12">
  <h2 class="title"><%= @instance.name %></h2>
  <p>Email: <%= @instance.email %></p>

  <div class="btn-group">
  </div>
  </div>
</div>